name: Pull Request

on: [pull_request]

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        command:
          - lint
          - test
          - type-check
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Cache Yarn'
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile
      - name: 'Run ${{ matrix.command }}'
        run: yarn ${{ matrix.command }}
        env:
          MAGIC_SECRET_KEY: ${{ secrets.MAGIC_SECRET_KEY }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
        env:
          MAGIC_SECRET_KEY: ${{ secrets.MAGIC_SECRET_KEY }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          CYPRESS_validToken: ${{ secrets.VALID_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

  commitlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if:
      github.actor != 'dependabot[bot]' && github.actor !=
      'dependabot-preview[bot]'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1

  auto-approve:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if:
      github.actor == 'dependabot[bot]' || github.actor ==
      'dependabot-preview[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
